apiVersion: v1
kind: Service
metadata:
  name: h-project
  labels:
    app: h-project
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: h-project
  type: ClusterIP
